DROP TABLE GUIDEINFOMAIN CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE GUIDE_CALCULATE CASCADE CONSTRAINTS;
DROP TABLE GUIDE_CALCULATEPAY_HISTORY CASCADE CONSTRAINTS;
DROP TABLE GUIDE_INFORMATION CASCADE CONSTRAINTS;
DROP TABLE GUIDE_RANK CASCADE CONSTRAINTS;
DROP TABLE GUIDE_RANK_HISTORY CASCADE CONSTRAINTS;
DROP TABLE GUIDE_WARNING_HISTORY CASCADE CONSTRAINTS;
DROP TABLE GUIDEATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_REVISEHISTORY CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_STATUSHISTORY CASCADE CONSTRAINTS;
DROP TABLE RESERVATION_MEMBER_INFO CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE REVIEWATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE TRAVEL CASCADE CONSTRAINTS;
DROP TABLE TRAVEL_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE TRAVEL_STATUS_HISTORY CASCADE CONSTRAINTS;
DROP TABLE TRAVELATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE TRAVELREFUND CASCADE CONSTRAINTS;
DROP TABLE WARNING_HISTORY CASCADE CONSTRAINTS;
DROP TABLE WISHLIST CASCADE CONSTRAINTS;
DROP TABLE ASKBOARD CASCADE CONSTRAINTS;
DROP TABLE GUIDE_APPLICATION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE BOARD_REVISE CASCADE CONSTRAINTS;
DROP TABLE DAY_SALE_STATICS CASCADE CONSTRAINTS;
DROP TABLE TRAVEL_OPTION CASCADE CONSTRAINTS;
DROP TABLE RESERVATION_STATUS CASCADE CONSTRAINTS;

-----------------------------------------------------------------------------------------------------

DROP TABLE ASKBOARD;

CREATE TABLE ASKBOARD
(
    ASKBOARD_NO    NUMBER NOT NULL,
    ASKBOARD_TITLE    VARCHAR2(500),
    ASKBOARD_CATEGORY    VARCHAR2(100),
    ASKBOARD_BODY    VARCHAR2(4000),
    ASKBOARD_PWD    VARCHAR2(500),
    ASKBOARD_STATUS    VARCHAR2(100),
    ASKBOARD_ASKDATE    DATE,
    TRAVEL_NO    NUMBER,
    ANSWER_BODY    VARCHAR2(4000),
    MEMBER_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN ASKBOARD.ASKBOARD_NO IS '문의코드';

COMMENT ON COLUMN ASKBOARD.ASKBOARD_TITLE IS '제목';

COMMENT ON COLUMN ASKBOARD.ASKBOARD_CATEGORY IS '문의 분류';

COMMENT ON COLUMN ASKBOARD.ASKBOARD_BODY IS '문의 내용';

COMMENT ON COLUMN ASKBOARD.ASKBOARD_PWD IS '비밀번호';

COMMENT ON COLUMN ASKBOARD.ASKBOARD_STATUS IS '문의 상태';

COMMENT ON COLUMN ASKBOARD.ASKBOARD_ASKDATE IS '문의 일시';

COMMENT ON COLUMN ASKBOARD.TRAVEL_NO IS '투어 상품번호';

COMMENT ON COLUMN ASKBOARD.ANSWER_BODY IS '답변 내용';

COMMENT ON COLUMN ASKBOARD.MEMBER_NO IS '회원번호';

COMMENT ON TABLE ASKBOARD IS '문의하기';

DROP INDEX 엔터티1_PK16;

CREATE UNIQUE INDEX 엔터티1_PK16 ON ASKBOARD
( ASKBOARD_NO );

ALTER TABLE ASKBOARD
DROP PRIMARY KEY;

ALTER TABLE ASKBOARD
 ADD CONSTRAINT 엔터티1_PK16 PRIMARY KEY ( ASKBOARD_NO )
 USING INDEX 엔터티1_PK16;


DROP TABLE BOARD;

CREATE TABLE BOARD
(
    BOARD_CATEGORY    VARCHAR2(500),
    BOARD_DATE    DATE,
    BOARD_TITLE    VARCHAR2(1000),
    BOARD_BODY    VARCHAR2(4000),
    BOARD_NO    NUMBER NOT NULL,
    BOARD_WRITER    NUMBER,
    BOARD_STATUS    VARCHAR2(100)
);

COMMENT ON COLUMN BOARD.BOARD_CATEGORY IS '종류';

COMMENT ON COLUMN BOARD.BOARD_DATE IS '등록날짜';

COMMENT ON COLUMN BOARD.BOARD_TITLE IS '제목';

COMMENT ON COLUMN BOARD.BOARD_BODY IS '내용';

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';

COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자';

COMMENT ON COLUMN BOARD.BOARD_STATUS IS '게시판 상태';

COMMENT ON TABLE BOARD IS '게시판';

DROP INDEX 엔터티1_PK19;

CREATE UNIQUE INDEX 엔터티1_PK19 ON BOARD
( BOARD_NO );

ALTER TABLE BOARD
DROP PRIMARY KEY;

ALTER TABLE BOARD
 ADD CONSTRAINT 엔터티1_PK19 PRIMARY KEY ( BOARD_NO )
 USING INDEX 엔터티1_PK19;


DROP TABLE BOARD_REVISE;

CREATE TABLE BOARD_REVISE
(
    BOARD_CATEGORY    VARCHAR2(100),
    REVISE_DATE    DATE,
    REVISE_CATEGORY    VARCHAR2(100),
    REVISE_BEFORE    VARCHAR2(4000),
    REVISE_AFTER    VARCHAR2(4000),
    BOARD_NO    NUMBER NOT NULL,
    BOARD_WRITER_NO    NUMBER
);

COMMENT ON COLUMN BOARD_REVISE.BOARD_CATEGORY IS '분류';

COMMENT ON COLUMN BOARD_REVISE.REVISE_DATE IS '변경날짜';

COMMENT ON COLUMN BOARD_REVISE.REVISE_CATEGORY IS '변경 종류';

COMMENT ON COLUMN BOARD_REVISE.REVISE_BEFORE IS '변경 전';

COMMENT ON COLUMN BOARD_REVISE.REVISE_AFTER IS '변경 후';

COMMENT ON COLUMN BOARD_REVISE.BOARD_NO IS '게시글 번호';

COMMENT ON COLUMN BOARD_REVISE.BOARD_WRITER_NO IS '작성자';

COMMENT ON TABLE BOARD_REVISE IS '게시판 수정이력';

DROP INDEX 엔터티1_PK20;

CREATE UNIQUE INDEX 엔터티1_PK20 ON BOARD_REVISE
( BOARD_NO );

ALTER TABLE BOARD_REVISE
DROP PRIMARY KEY;

ALTER TABLE BOARD_REVISE
 ADD CONSTRAINT 엔터티1_PK20 PRIMARY KEY ( BOARD_NO )
 USING INDEX 엔터티1_PK20;


DROP TABLE DAY_SALE_STATICS;

CREATE TABLE DAY_SALE_STATICS
(
    CLEAR_PROFIT    NUMBER NOT NULL,
    TOTAL_SALES    NUMBER NOT NULL,
    GUIDE_PAY_PRICE    NUMBER NOT NULL,
    OTHERS_PROFIT    NUMBER NOT NULL,
    ADDTION_EXPENSE    NUMBER NOT NULL,
    날짜    DATE NOT NULL
);

COMMENT ON COLUMN DAY_SALE_STATICS.CLEAR_PROFIT IS '순이익';

COMMENT ON COLUMN DAY_SALE_STATICS.TOTAL_SALES IS '총매출';

COMMENT ON COLUMN DAY_SALE_STATICS.GUIDE_PAY_PRICE IS '가이드정산지급액';

COMMENT ON COLUMN DAY_SALE_STATICS.OTHERS_PROFIT IS '기타이익';

COMMENT ON COLUMN DAY_SALE_STATICS.ADDTION_EXPENSE IS '부가 지출';

COMMENT ON COLUMN DAY_SALE_STATICS.날짜 IS '날짜';

COMMENT ON TABLE DAY_SALE_STATICS IS '일 매출 통계';

DROP INDEX 엔터티1_PK24;

CREATE UNIQUE INDEX 엔터티1_PK24 ON DAY_SALE_STATICS
( 날짜 );

ALTER TABLE DAY_SALE_STATICS
DROP PRIMARY KEY;

ALTER TABLE DAY_SALE_STATICS
 ADD CONSTRAINT 엔터티1_PK24 PRIMARY KEY ( 날짜 )
 USING INDEX 엔터티1_PK24;


DROP TABLE GUIDE_APPLICATION_HISTORY;

CREATE TABLE GUIDE_APPLICATION_HISTORY
(
    APPLICATION_NO    NUMBER NOT NULL,
    APPLICATION_DATE    DATE NOT NULL,
    APPLICATION_STATUS    VARCHAR2(100) NOT NULL,
    APPLICATION_RETURN_REASON    VARCHAR2(4000),
    APPLICATION_REJECT_REASON    VARCHAR2(4000),
    MEMBER_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN GUIDE_APPLICATION_HISTORY.APPLICATION_NO IS '신청승인이력변호';

COMMENT ON COLUMN GUIDE_APPLICATION_HISTORY.APPLICATION_DATE IS '이력발생일자';

COMMENT ON COLUMN GUIDE_APPLICATION_HISTORY.APPLICATION_STATUS IS '승인상태';

COMMENT ON COLUMN GUIDE_APPLICATION_HISTORY.APPLICATION_RETURN_REASON IS '반려사유';

COMMENT ON COLUMN GUIDE_APPLICATION_HISTORY.APPLICATION_REJECT_REASON IS '거절사유';

COMMENT ON COLUMN GUIDE_APPLICATION_HISTORY.MEMBER_NO IS '회원번호';

COMMENT ON TABLE GUIDE_APPLICATION_HISTORY IS '가이드신청승인이력';

DROP INDEX 엔터티1_PK5;

CREATE UNIQUE INDEX 엔터티1_PK5 ON GUIDE_APPLICATION_HISTORY
( APPLICATION_NO );

ALTER TABLE GUIDE_APPLICATION_HISTORY
DROP PRIMARY KEY;

ALTER TABLE GUIDE_APPLICATION_HISTORY
 ADD CONSTRAINT 엔터티1_PK5 PRIMARY KEY ( APPLICATION_NO )
 USING INDEX 엔터티1_PK5;


DROP TABLE GUIDE_CALCULATE;

CREATE TABLE GUIDE_CALCULATE
(
    CALCULATE_NO    NUMBER NOT NULL,
    PAYMENT_NO    VARCHAR2(100) NOT NULL,
    GUIDE_CALCULATE_SUM    VARCHAR2(100) NOT NULL,
    GUIDE_CALCULATE_STATUS    VARCHAR2(500) NOT NULL,
    GUIDE_NO    NUMBER NOT NULL,
    TRAVEL_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN GUIDE_CALCULATE.CALCULATE_NO IS '정산코드';

COMMENT ON COLUMN GUIDE_CALCULATE.PAYMENT_NO IS '결제코드';

COMMENT ON COLUMN GUIDE_CALCULATE.GUIDE_CALCULATE_SUM IS '금액확인여부';

COMMENT ON COLUMN GUIDE_CALCULATE.GUIDE_CALCULATE_STATUS IS '구분';

COMMENT ON COLUMN GUIDE_CALCULATE.GUIDE_NO IS '가이드회원번호';

COMMENT ON COLUMN GUIDE_CALCULATE.TRAVEL_NO IS '상품번호';

COMMENT ON TABLE GUIDE_CALCULATE IS '정산';

DROP INDEX 엔터티1_PK15;

CREATE UNIQUE INDEX 엔터티1_PK15 ON GUIDE_CALCULATE
( GUIDE_NO,CALCULATE_NO );

ALTER TABLE GUIDE_CALCULATE
DROP PRIMARY KEY;

ALTER TABLE GUIDE_CALCULATE
 ADD CONSTRAINT 엔터티1_PK15 PRIMARY KEY ( GUIDE_NO,CALCULATE_NO )
 USING INDEX 엔터티1_PK15;


DROP TABLE GUIDE_CALCULATEPAY_HISTORY;

CREATE TABLE GUIDE_CALCULATEPAY_HISTORY
(
    PAY_DATE    DATE NOT NULL,
    PAY_PRICE    NUMBER NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    CALCULATE_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN GUIDE_CALCULATEPAY_HISTORY.PAY_DATE IS '지급날짜';

COMMENT ON COLUMN GUIDE_CALCULATEPAY_HISTORY.PAY_PRICE IS '지급액';

COMMENT ON COLUMN GUIDE_CALCULATEPAY_HISTORY.MEMBER_NO IS '가이드회원번호';

COMMENT ON COLUMN GUIDE_CALCULATEPAY_HISTORY.CALCULATE_NO IS '정산코드';

COMMENT ON TABLE GUIDE_CALCULATEPAY_HISTORY IS '가이드 정산 지급 이력';

DROP INDEX 엔터티1_PK22;

CREATE UNIQUE INDEX 엔터티1_PK22 ON GUIDE_CALCULATEPAY_HISTORY
( MEMBER_NO,CALCULATE_NO );

ALTER TABLE GUIDE_CALCULATEPAY_HISTORY
DROP PRIMARY KEY;

ALTER TABLE GUIDE_CALCULATEPAY_HISTORY
 ADD CONSTRAINT 엔터티1_PK22 PRIMARY KEY ( MEMBER_NO,CALCULATE_NO )
 USING INDEX 엔터티1_PK22;


DROP TABLE GUIDE_INFORMATION;

CREATE TABLE GUIDE_INFORMATION
(
    MEMBER_NO    NUMBER NOT NULL,
    GUIDE_NAME    VARCHAR2(500) NOT NULL,
    GUIDE_EMAIL    VARCHAR2(1000) NOT NULL,
    GUIDE_BANK    VARCHAR2(500) NOT NULL,
    GUIDE_ACCOUNT    VARCHAR2(500) NOT NULL,
    GUIDE_INTRO    VARCHAR2(4000) NOT NULL,
    GUIDE_STATUS    VARCHAR2(500) NOT NULL,
    GUIDE_RANK    VARCHAR2(100),
    GUIDE_WARNING_COUNT    NUMBER,
    GUIDE_APPROVE    VARCHAR2(100),
    GUIDE_ENROLLDATE    DATE,
    GUIDE_CANCLEDATE    DATE
);

COMMENT ON COLUMN GUIDE_INFORMATION.MEMBER_NO IS '회원번호';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_NAME IS '실명';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_EMAIL IS '정산용이메일';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_BANK IS '은행명';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_ACCOUNT IS '계좌번호';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_INTRO IS '경력및자기소개';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_STATUS IS '가이드활성화상태';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_RANK IS '가이드등급';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_WARNING_COUNT IS '경고횟수';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_APPROVE IS '승인여부';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_ENROLLDATE IS '등록날짜';

COMMENT ON COLUMN GUIDE_INFORMATION.GUIDE_CANCLEDATE IS '취소 날짜';

COMMENT ON TABLE GUIDE_INFORMATION IS '가이드추가정보';

DROP INDEX 엔터티1_PK1;

CREATE UNIQUE INDEX 엔터티1_PK1 ON GUIDE_INFORMATION
( MEMBER_NO );

ALTER TABLE GUIDE_INFORMATION
DROP PRIMARY KEY;

ALTER TABLE GUIDE_INFORMATION
 ADD CONSTRAINT 엔터티1_PK1 PRIMARY KEY ( MEMBER_NO )
 USING INDEX 엔터티1_PK1;


DROP TABLE GUIDE_RANK;

CREATE TABLE GUIDE_RANK
(
    RANK_CODE    VARCHAR2(100) NOT NULL,
    RANK_NAME    VARCHAR2(300) NOT NULL,
    GUIDE_COMMISSION    NUMBER NOT NULL
);

COMMENT ON COLUMN GUIDE_RANK.RANK_CODE IS '등급코드';

COMMENT ON COLUMN GUIDE_RANK.RANK_NAME IS '등급명';

COMMENT ON COLUMN GUIDE_RANK.GUIDE_COMMISSION IS '수수료율';

COMMENT ON TABLE GUIDE_RANK IS '가이드등급';

DROP INDEX 엔터티1_PK2;

CREATE UNIQUE INDEX 엔터티1_PK2 ON GUIDE_RANK
( RANK_CODE );

ALTER TABLE GUIDE_RANK
DROP PRIMARY KEY;

ALTER TABLE GUIDE_RANK
 ADD CONSTRAINT 엔터티1_PK2 PRIMARY KEY ( RANK_CODE )
 USING INDEX 엔터티1_PK2;


DROP TABLE GUIDE_RANK_HISTORY;

CREATE TABLE GUIDE_RANK_HISTORY
(
    RANK_CODE    VARCHAR2(100) NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    RANK_CHANGE_YEAR    DATE NOT NULL,
    RANK_CHANGE_QUARTER    NUMBER NOT NULL,
    BEFORE_CODE    VARCHAR2(100) NOT NULL,
    AFTER_CODE    VARCHAR2(100) NOT NULL,
    RANK_CHANGE_DAY    DATE NOT NULL
);

COMMENT ON COLUMN GUIDE_RANK_HISTORY.RANK_CODE IS '등급코드';

COMMENT ON COLUMN GUIDE_RANK_HISTORY.MEMBER_NO IS '회원번호';

COMMENT ON COLUMN GUIDE_RANK_HISTORY.RANK_CHANGE_YEAR IS '변경반영년도';

COMMENT ON COLUMN GUIDE_RANK_HISTORY.RANK_CHANGE_QUARTER IS '변경반영분기';

COMMENT ON COLUMN GUIDE_RANK_HISTORY.BEFORE_CODE IS '이전등급';

COMMENT ON COLUMN GUIDE_RANK_HISTORY.AFTER_CODE IS '변경후등급';

COMMENT ON COLUMN GUIDE_RANK_HISTORY.RANK_CHANGE_DAY IS '변경등록일자';

COMMENT ON TABLE GUIDE_RANK_HISTORY IS '가이드등급변경이력';

DROP INDEX 엔터티1_PK3;

CREATE UNIQUE INDEX 엔터티1_PK3 ON GUIDE_RANK_HISTORY
( RANK_CODE,MEMBER_NO,RANK_CHANGE_YEAR,RANK_CHANGE_QUARTER );

ALTER TABLE GUIDE_RANK_HISTORY
DROP PRIMARY KEY;

ALTER TABLE GUIDE_RANK_HISTORY
 ADD CONSTRAINT 엔터티1_PK3 PRIMARY KEY ( RANK_CODE,MEMBER_NO,RANK_CHANGE_YEAR,RANK_CHANGE_QUARTER )
 USING INDEX 엔터티1_PK3;


DROP TABLE GUIDE_WARNING_HISTORY;

CREATE TABLE GUIDE_WARNING_HISTORY
(
    WARNING_REASON    VARCHAR2(4000) NOT NULL,
    WARNING_DATE    DATE NOT NULL,
    MEMBER_NO    NUMBER
);

COMMENT ON COLUMN GUIDE_WARNING_HISTORY.WARNING_REASON IS '경고 사유';

COMMENT ON COLUMN GUIDE_WARNING_HISTORY.WARNING_DATE IS '경고 날짜';

COMMENT ON COLUMN GUIDE_WARNING_HISTORY.MEMBER_NO IS '회원번호';

COMMENT ON TABLE GUIDE_WARNING_HISTORY IS '가이드 경고 이력';

DROP INDEX 엔터티1_PK21;


ALTER TABLE GUIDE_WARNING_HISTORY
DROP PRIMARY KEY;


DROP TABLE GUIDEATTACHMENT;

CREATE TABLE GUIDEATTACHMENT
(
    G_ATTACHMENT_NO_1    NUMBER NOT NULL,
    ORIGINAL_NAME_1    VARCHAR2(255) NOT NULL,
    SAVED_NAME_1    VARCHAR2(255) NOT NULL,
    SAVE_PATH_1    VARCHAR2(1000) NOT NULL,
    FILE_TYPE_1    VARCHAR2(5),
    THUMBNAIL_PATH_1    VARCHAR2(255),
    ATTACHMENT_STATUS_1    VARCHAR2(1),
    REF_GUIDE_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN GUIDEATTACHMENT.G_ATTACHMENT_NO_1 IS '첨부파일 코드';

COMMENT ON COLUMN GUIDEATTACHMENT.ORIGINAL_NAME_1 IS '첨부파일 이름';

COMMENT ON COLUMN GUIDEATTACHMENT.SAVED_NAME_1 IS '저장 이름';

COMMENT ON COLUMN GUIDEATTACHMENT.SAVE_PATH_1 IS '저장 경로';

COMMENT ON COLUMN GUIDEATTACHMENT.FILE_TYPE_1 IS '파일 타입';

COMMENT ON COLUMN GUIDEATTACHMENT.THUMBNAIL_PATH_1 IS '썸네일 경로';

COMMENT ON COLUMN GUIDEATTACHMENT.ATTACHMENT_STATUS_1 IS '게시판  상태';

COMMENT ON COLUMN GUIDEATTACHMENT.REF_GUIDE_NO IS '가이드 번호';

COMMENT ON TABLE GUIDEATTACHMENT IS '가이드등록첨부파일';

DROP INDEX 엔터티1_1_PK12;

CREATE UNIQUE INDEX 엔터티1_1_PK12 ON GUIDEATTACHMENT
( REF_GUIDE_NO,G_ATTACHMENT_NO_1 );

ALTER TABLE GUIDEATTACHMENT
DROP PRIMARY KEY;

ALTER TABLE GUIDEATTACHMENT
 ADD CONSTRAINT 엔터티1_1_PK12 PRIMARY KEY ( REF_GUIDE_NO,G_ATTACHMENT_NO_1 )
 USING INDEX 엔터티1_1_PK12;


DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
    MEMBER_NO    NUMBER NOT NULL,
    MEMBER_ID    VARCHAR2(300) NOT NULL,
    MEMBER_PWD    VARCHAR2(500) NOT NULL,
    MEMBER_NICKNAME    VARCHAR2(500) NOT NULL,
    MEMBER_EMAIL    VARCHAR2(1000) NOT NULL,
    MEMBER_PHONE    VARCHAR2(500) NOT NULL,
    MEMBER_STATUS    VARCHAR2(100) NOT NULL,
    MEMBER_ROLE    VARCHAR2(100) NOT NULL,
    MEMBER_ENROLLDATE    DATE NOT NULL,
    GUIDE_RANK    VARCHAR2(100)
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';

COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '패스워드';

COMMENT ON COLUMN MEMBER.MEMBER_NICKNAME IS '활동회원명';

COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '회원이메일';

COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '핸드폰번호';

COMMENT ON COLUMN MEMBER.MEMBER_STATUS IS '탈퇴여부';

COMMENT ON COLUMN MEMBER.MEMBER_ROLE IS '회원구분';

COMMENT ON COLUMN MEMBER.MEMBER_ENROLLDATE IS '가입일';

COMMENT ON COLUMN MEMBER.GUIDE_RANK IS '가이드등급';

COMMENT ON TABLE MEMBER IS '회원';

DROP INDEX 엔터티1_PK;

CREATE UNIQUE INDEX 엔터티1_PK ON MEMBER
( MEMBER_NO );

ALTER TABLE MEMBER
DROP PRIMARY KEY;

ALTER TABLE MEMBER
 ADD CONSTRAINT 엔터티1_PK PRIMARY KEY ( MEMBER_NO )
 USING INDEX 엔터티1_PK;


DROP TABLE MEMBER_REVISEHISTORY;

CREATE TABLE MEMBER_REVISEHISTORY
(
    REVISE_DATE    DATE,
    REVISE_BEFORE    VARCHAR2(4000),
    REVISE_AFTER    VARCHAR2(4000),
    REVISE_CATEGORY    VARCHAR2(100),
    MEMBER_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN MEMBER_REVISEHISTORY.REVISE_DATE IS '변경날짜';

COMMENT ON COLUMN MEMBER_REVISEHISTORY.REVISE_BEFORE IS '변경전 값';

COMMENT ON COLUMN MEMBER_REVISEHISTORY.REVISE_AFTER IS '변경후 값';

COMMENT ON COLUMN MEMBER_REVISEHISTORY.REVISE_CATEGORY IS '변경종류';

COMMENT ON COLUMN MEMBER_REVISEHISTORY.MEMBER_NO IS '회원번호';

COMMENT ON TABLE MEMBER_REVISEHISTORY IS '개인정보수정이력';

DROP INDEX 엔터티1_PK18;

CREATE UNIQUE INDEX 엔터티1_PK18 ON MEMBER_REVISEHISTORY
( MEMBER_NO );

ALTER TABLE MEMBER_REVISEHISTORY
DROP PRIMARY KEY;

ALTER TABLE MEMBER_REVISEHISTORY
 ADD CONSTRAINT 엔터티1_PK18 PRIMARY KEY ( MEMBER_NO )
 USING INDEX 엔터티1_PK18;


DROP TABLE PAYMENT;

CREATE TABLE PAYMENT
(
    PAYMENT_NO    VARCHAR2(100) NOT NULL,
    PAYMENT_DATE    TIMESTAMP NOT NULL,
    PAYMENT_CATEGORY    VARCHAR2(100) NOT NULL,
    PAYMENT_STATUS    VARCHAR2(100) NOT NULL,
    PAYMENT_APPROVAL_NO    NUMBER,
    TRAVEL_RESERVATION_NO    VARCHAR2(100),
    MEMBER_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN PAYMENT.PAYMENT_NO IS '결제번호';

COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '결제일시';

COMMENT ON COLUMN PAYMENT.PAYMENT_CATEGORY IS '결제구분';

COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS IS '결제상태';

COMMENT ON COLUMN PAYMENT.PAYMENT_APPROVAL_NO IS '카드승인번호';

COMMENT ON COLUMN PAYMENT.TRAVEL_RESERVATION_NO IS '투어예약번호';

COMMENT ON COLUMN PAYMENT.MEMBER_NO IS '회원번호';

COMMENT ON TABLE PAYMENT IS '결제';

DROP INDEX 엔터티1_PK10;

CREATE UNIQUE INDEX 엔터티1_PK10 ON PAYMENT
( MEMBER_NO,PAYMENT_NO );

ALTER TABLE PAYMENT
DROP PRIMARY KEY;

ALTER TABLE PAYMENT
 ADD CONSTRAINT 엔터티1_PK10 PRIMARY KEY ( MEMBER_NO,PAYMENT_NO )
 USING INDEX 엔터티1_PK10;


DROP TABLE PAYMENT_STATUSHISTORY;

CREATE TABLE PAYMENT_STATUSHISTORY
(
    PAYMENT_HISTORY_NO    NUMBER NOT NULL,
    PAYMENT_HISTORY_DATE    DATE NOT NULL,
    PAYMENT_HISTORY_REASON    VARCHAR2(4000) NOT NULL,
    PAYMENT_NO    VARCHAR2(100),
    MEMBER_NO    NUMBER
);

COMMENT ON COLUMN PAYMENT_STATUSHISTORY.PAYMENT_HISTORY_NO IS '결제상태변경이력번호';

COMMENT ON COLUMN PAYMENT_STATUSHISTORY.PAYMENT_HISTORY_DATE IS '이력발생일자';

COMMENT ON COLUMN PAYMENT_STATUSHISTORY.PAYMENT_HISTORY_REASON IS '이력발생사유 (환불요청 사유)';

COMMENT ON COLUMN PAYMENT_STATUSHISTORY.PAYMENT_NO IS '결제번호';

COMMENT ON COLUMN PAYMENT_STATUSHISTORY.MEMBER_NO IS '회원번호';

COMMENT ON TABLE PAYMENT_STATUSHISTORY IS '결제상태변경이력';

DROP INDEX 엔터티1_PK11;

CREATE UNIQUE INDEX 엔터티1_PK11 ON PAYMENT_STATUSHISTORY
( PAYMENT_HISTORY_NO );

ALTER TABLE PAYMENT_STATUSHISTORY
DROP PRIMARY KEY;

ALTER TABLE PAYMENT_STATUSHISTORY
 ADD CONSTRAINT 엔터티1_PK11 PRIMARY KEY ( PAYMENT_HISTORY_NO )
 USING INDEX 엔터티1_PK11;


DROP TABLE RESERVATION_MEMBER_INFO;

CREATE TABLE RESERVATION_MEMBER_INFO
(
    TRAVEL_RESERVATION_NO    VARCHAR2(100) NOT NULL,
    KOR_FIRST_NAME    VARCHAR2(50) NOT NULL,
    ENG_FIRST_NAME    VARCHAR2(100) NOT NULL,
    GENDER    VARCHAR2(50) NOT NULL,
    PHONE    VARCHAR2(100) NOT NULL,
    MEMBER_EMAIL    VARCHAR2(300),
    BIRTH    DATE NOT NULL
);

COMMENT ON COLUMN RESERVATION_MEMBER_INFO.TRAVEL_RESERVATION_NO IS '투어예약번호';

COMMENT ON COLUMN RESERVATION_MEMBER_INFO.KOR_FIRST_NAME IS '한글이름';

COMMENT ON COLUMN RESERVATION_MEMBER_INFO.ENG_FIRST_NAME IS '영문이름';

COMMENT ON COLUMN RESERVATION_MEMBER_INFO.GENDER IS '성별';

COMMENT ON COLUMN RESERVATION_MEMBER_INFO.PHONE IS '휴대폰번호';

COMMENT ON COLUMN RESERVATION_MEMBER_INFO.MEMBER_EMAIL IS '이메일';

COMMENT ON COLUMN RESERVATION_MEMBER_INFO.BIRTH IS '법정생년월일';

COMMENT ON TABLE RESERVATION_MEMBER_INFO IS '투어예약별여행자정보';

DROP INDEX 엔터티1_PK9;

CREATE UNIQUE INDEX 엔터티1_PK9 ON RESERVATION_MEMBER_INFO
( TRAVEL_RESERVATION_NO,PHONE );

ALTER TABLE RESERVATION_MEMBER_INFO
DROP PRIMARY KEY;

ALTER TABLE RESERVATION_MEMBER_INFO
 ADD CONSTRAINT 엔터티1_PK9 PRIMARY KEY ( TRAVEL_RESERVATION_NO,PHONE )
 USING INDEX 엔터티1_PK9;


DROP TABLE REVIEWATTACHMENT;

CREATE TABLE REVIEWATTACHMENT
(
    R_ATTACHMENT_NO_1    NUMBER,
    REF_BOARD_NO_1    NUMBER,
    ORIGINAL_NAME_1    VARCHAR2(255),
    SAVED_NAME_1    VARCHAR2(255),
    SAVE_PATH_1    VARCHAR2(1000),
    FILE_TYPE_1    VARCHAR2(5),
    THUMBNAIL_PATH_1    VARCHAR2(255),
    ATTACHMENT_STATUS_1    VARCHAR2(1),
    TRAVEL_RESERVATION_NO    VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN REVIEWATTACHMENT.R_ATTACHMENT_NO_1 IS '첨부파일 코드';

COMMENT ON COLUMN REVIEWATTACHMENT.REF_BOARD_NO_1 IS '게시판 번호';

COMMENT ON COLUMN REVIEWATTACHMENT.ORIGINAL_NAME_1 IS '첨부파일 이름';

COMMENT ON COLUMN REVIEWATTACHMENT.SAVED_NAME_1 IS '저장 이름';

COMMENT ON COLUMN REVIEWATTACHMENT.SAVE_PATH_1 IS '저장 경로';

COMMENT ON COLUMN REVIEWATTACHMENT.FILE_TYPE_1 IS '파일 타입';

COMMENT ON COLUMN REVIEWATTACHMENT.THUMBNAIL_PATH_1 IS '썸네일 경로';

COMMENT ON COLUMN REVIEWATTACHMENT.ATTACHMENT_STATUS_1 IS '게시판  상태';

COMMENT ON COLUMN REVIEWATTACHMENT.TRAVEL_RESERVATION_NO IS '투어예약번호';

COMMENT ON TABLE REVIEWATTACHMENT IS '리뷰 첨부파일';

DROP INDEX 엔터티1_1_PK12;

CREATE UNIQUE INDEX 엔터티1_1_PK12 ON REVIEWATTACHMENT
( TRAVEL_RESERVATION_NO );

ALTER TABLE REVIEWATTACHMENT
DROP PRIMARY KEY;

ALTER TABLE REVIEWATTACHMENT
 ADD CONSTRAINT 엔터티1_1_PK12 PRIMARY KEY ( TRAVEL_RESERVATION_NO )
 USING INDEX 엔터티1_1_PK12;


DROP TABLE REVIEWBOARD;

CREATE TABLE REVIEWBOARD
(
    TRAVEL_NO    NUMBER NOT NULL,
    REVIEW_GRADE    NUMBER,
    TRAVEL_RESERVATION_NO    VARCHAR2(100) NOT NULL,
    BOARD_NO    NUMBER,
    BOARD_TYPE    VARCHAR2(100),
    CATEGORY_CODE    NUMBER,
    BOARD_TITLE    VARCHAR2(100),
    BOARD_BODY    VARCHAR2(4000),
    BOARD_WRITER_MEMBER_NO    NUMBER,
    BOARD_COUNT    NUMBER,
    CREATED_DATE    DATE,
    MODIFIED_DATE    DATE,
    BOARD_STATUS    VARCHAR2(100)
);

COMMENT ON COLUMN REVIEWBOARD.TRAVEL_NO IS '투어상품번호';

COMMENT ON COLUMN REVIEWBOARD.REVIEW_GRADE IS '투어 별점';

COMMENT ON COLUMN REVIEWBOARD.TRAVEL_RESERVATION_NO IS '투어예약번호';

COMMENT ON COLUMN REVIEWBOARD.BOARD_NO IS '게시판 번호';

COMMENT ON COLUMN REVIEWBOARD.BOARD_TYPE IS '게시판 유형';

COMMENT ON COLUMN REVIEWBOARD.CATEGORY_CODE IS '카테고리 코드';

COMMENT ON COLUMN REVIEWBOARD.BOARD_TITLE IS '게시판 제목';

COMMENT ON COLUMN REVIEWBOARD.BOARD_BODY IS '게시판 내용';

COMMENT ON COLUMN REVIEWBOARD.BOARD_WRITER_MEMBER_NO IS '게시판 작성자';

COMMENT ON COLUMN REVIEWBOARD.BOARD_COUNT IS '게시판 조회';

COMMENT ON COLUMN REVIEWBOARD.CREATED_DATE IS '작성날짜';

COMMENT ON COLUMN REVIEWBOARD.MODIFIED_DATE IS '수정날짜';

COMMENT ON COLUMN REVIEWBOARD.BOARD_STATUS IS '게시판 상태';

COMMENT ON TABLE REVIEWBOARD IS '이용후기';

DROP INDEX 엔터티1_PK13;

CREATE UNIQUE INDEX 엔터티1_PK13 ON REVIEWBOARD
( TRAVEL_RESERVATION_NO );

ALTER TABLE REVIEWBOARD
DROP PRIMARY KEY;

ALTER TABLE REVIEWBOARD
 ADD CONSTRAINT 엔터티1_PK13 PRIMARY KEY ( TRAVEL_RESERVATION_NO )
 USING INDEX 엔터티1_PK13;


DROP TABLE TRAVEL;

CREATE TABLE TRAVEL
(
    TRAVEL_NO    NUMBER NOT NULL,
    TRAVEL_COST    NUMBER NOT NULL,
    TRAVEL_STARTDATE    DATE NOT NULL,
    TRAVEL_ENDDATE    DATE NOT NULL,
    TRAVEL_INTRO    VARCHAR2(4000) NOT NULL,
    TRAVEL_COURSE    VARCHAR2(4000) NOT NULL,
    TRAVEL_INFORMATION    VARCHAR2(4000) NOT NULL,
    TRAVEL_ENROLL_DATE    DATE NOT NULL,
    TRAVEL_CHANGE_DATE    DATE NOT NULL,
    TRAVEL_ENROLL_STATUS    VARCHAR2(100) NOT NULL,
    TRAVEL_SELL_STATUS    VARCHAR2(100),
    GUIDE_NO    NUMBER NOT NULL,
    TRAVEL_MAX    NUMBER NOT NULL,
    TRAVEL_NAME    VARCHAR2(1000) NOT NULL,
    TRAVEL_SUMMERY_1    VARCHAR2(1000) NOT NULL,
    SHOW_STATUS    VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN TRAVEL.TRAVEL_NO IS '투어상품번호';

COMMENT ON COLUMN TRAVEL.TRAVEL_COST IS '상품기본금액';

COMMENT ON COLUMN TRAVEL.TRAVEL_STARTDATE IS '투어시작일자';

COMMENT ON COLUMN TRAVEL.TRAVEL_ENDDATE IS '투어종료일자';

COMMENT ON COLUMN TRAVEL.TRAVEL_INTRO IS '투어소개';

COMMENT ON COLUMN TRAVEL.TRAVEL_COURSE IS '코스안내';

COMMENT ON COLUMN TRAVEL.TRAVEL_INFORMATION IS '안내사항';

COMMENT ON COLUMN TRAVEL.TRAVEL_ENROLL_DATE IS '투어등록일자';

COMMENT ON COLUMN TRAVEL.TRAVEL_CHANGE_DATE IS '투어변경일자';

COMMENT ON COLUMN TRAVEL.TRAVEL_ENROLL_STATUS IS '투어등록상태';

COMMENT ON COLUMN TRAVEL.TRAVEL_SELL_STATUS IS '판매상태';

COMMENT ON COLUMN TRAVEL.GUIDE_NO IS '가이드회원번호';

COMMENT ON COLUMN TRAVEL.TRAVEL_MAX IS '투어최대인원';

COMMENT ON COLUMN TRAVEL.TRAVEL_NAME IS '상품명';

COMMENT ON COLUMN TRAVEL.TRAVEL_SUMMERY_1 IS '간단한소개';

COMMENT ON COLUMN TRAVEL.SHOW_STATUS IS '노출여부';

COMMENT ON TABLE TRAVEL IS '투어상품';

DROP INDEX 엔터티1_PK6;

CREATE UNIQUE INDEX 엔터티1_PK6 ON TRAVEL
( TRAVEL_NO );

ALTER TABLE TRAVEL
DROP PRIMARY KEY;

ALTER TABLE TRAVEL
 ADD CONSTRAINT 엔터티1_PK6 PRIMARY KEY ( TRAVEL_NO )
 USING INDEX 엔터티1_PK6;


DROP TABLE TRAVEL_OPTION;

CREATE TABLE TRAVEL_OPTION
(
    OPTION_NAME    VARCHAR2(500) NOT NULL,
    OPTION_PRICE    NUMBER NOT NULL,
    OPTION_CODE    NUMBER NOT NULL,
    TRAVEL_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN TRAVEL_OPTION.OPTION_NAME IS '옵션명';

COMMENT ON COLUMN TRAVEL_OPTION.OPTION_PRICE IS '가격';

COMMENT ON COLUMN TRAVEL_OPTION.OPTION_CODE IS '옵션코드';

COMMENT ON COLUMN TRAVEL_OPTION.TRAVEL_NO IS '투어상품번호';

COMMENT ON TABLE TRAVEL_OPTION IS '옵션';

DROP INDEX 엔터티1_PK17;

CREATE UNIQUE INDEX 엔터티1_PK17 ON TRAVEL_OPTION
( OPTION_CODE,TRAVEL_NO );

ALTER TABLE TRAVEL_OPTION
DROP PRIMARY KEY;

ALTER TABLE TRAVEL_OPTION
 ADD CONSTRAINT 엔터티1_PK17 PRIMARY KEY ( OPTION_CODE,TRAVEL_NO )
 USING INDEX 엔터티1_PK17;


DROP TABLE TRAVEL_RESERVATION;

CREATE TABLE TRAVEL_RESERVATION
(
    TRAVEL_RESERVATION_NO    VARCHAR2(100) NOT NULL,
    TRAVEL_RESERVATION_DATE    DATE NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    TRAVEL_NO    NUMBER NOT NULL,
    CALCULATE_NO    NUMBER NOT NULL,
    GUIDE_NO    NUMBER NOT NULL,
    RESERVATION_STATUS    VARCHAR2(100) NOT NULL,
    OPTION_CODE    NUMBER
);

COMMENT ON COLUMN TRAVEL_RESERVATION.TRAVEL_RESERVATION_NO IS '투어예약번호';

COMMENT ON COLUMN TRAVEL_RESERVATION.TRAVEL_RESERVATION_DATE IS '예약일시';

COMMENT ON COLUMN TRAVEL_RESERVATION.MEMBER_NO IS '회원번호';

COMMENT ON COLUMN TRAVEL_RESERVATION.TRAVEL_NO IS '투어상품번호';

COMMENT ON COLUMN TRAVEL_RESERVATION.CALCULATE_NO IS '정산코드';

COMMENT ON COLUMN TRAVEL_RESERVATION.GUIDE_NO IS '가이드회원번호';

COMMENT ON COLUMN TRAVEL_RESERVATION.RESERVATION_STATUS IS '예약상태';

COMMENT ON COLUMN TRAVEL_RESERVATION.OPTION_CODE IS '옵션코드';

COMMENT ON TABLE TRAVEL_RESERVATION IS '투어예약';

DROP INDEX 엔터티1_PK8;

CREATE UNIQUE INDEX 엔터티1_PK8 ON TRAVEL_RESERVATION
( TRAVEL_RESERVATION_NO );

ALTER TABLE TRAVEL_RESERVATION
DROP PRIMARY KEY;

ALTER TABLE TRAVEL_RESERVATION
 ADD CONSTRAINT 엔터티1_PK8 PRIMARY KEY ( TRAVEL_RESERVATION_NO )
 USING INDEX 엔터티1_PK8;


DROP TABLE TRAVEL_STATUS_HISTORY;

CREATE TABLE TRAVEL_STATUS_HISTORY
(
    TRAVEL_STATUS_HISTORY_NO    NUMBER NOT NULL,
    TRAVEL_STATUS    VARCHAR2(100) NOT NULL,
    STATUS_DATE    DATE NOT NULL,
    TRAVEL_SALE_STATUS    VARCHAR2(4000),
    TRAVEL_RETURN_REASON    VARCHAR2(4000),
    TRAVEL_REJECT_REASON    VARCHAR2(4000),
    TRAVEL_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN TRAVEL_STATUS_HISTORY.TRAVEL_STATUS_HISTORY_NO IS '투어상태변경이력번호';

COMMENT ON COLUMN TRAVEL_STATUS_HISTORY.TRAVEL_STATUS IS '투어상태';

COMMENT ON COLUMN TRAVEL_STATUS_HISTORY.STATUS_DATE IS '이력발생일자';

COMMENT ON COLUMN TRAVEL_STATUS_HISTORY.TRAVEL_SALE_STATUS IS '판매상태';

COMMENT ON COLUMN TRAVEL_STATUS_HISTORY.TRAVEL_RETURN_REASON IS '반려사유';

COMMENT ON COLUMN TRAVEL_STATUS_HISTORY.TRAVEL_REJECT_REASON IS '거절사유';

COMMENT ON COLUMN TRAVEL_STATUS_HISTORY.TRAVEL_NO IS '투어상품번호';

COMMENT ON TABLE TRAVEL_STATUS_HISTORY IS '투어상태변경이력';

DROP INDEX 엔터티1_PK7;

CREATE UNIQUE INDEX 엔터티1_PK7 ON TRAVEL_STATUS_HISTORY
( TRAVEL_STATUS_HISTORY_NO );

ALTER TABLE TRAVEL_STATUS_HISTORY
DROP PRIMARY KEY;

ALTER TABLE TRAVEL_STATUS_HISTORY
 ADD CONSTRAINT 엔터티1_PK7 PRIMARY KEY ( TRAVEL_STATUS_HISTORY_NO )
 USING INDEX 엔터티1_PK7;


DROP TABLE TRAVELATTACHMENT;

CREATE TABLE TRAVELATTACHMENT
(
    T_ATTACHMENT_NO_1    NUMBER NOT NULL,
    ORIGINAL_NAME_1    VARCHAR2(255) NOT NULL,
    SAVED_NAME_1    VARCHAR2(255) NOT NULL,
    SAVE_PATH_1    VARCHAR2(1000) NOT NULL,
    FILE_TYPE_1    VARCHAR2(5),
    THUMBNAIL_PATH_1    VARCHAR2(255),
    ATTACHMENT_STATUS_1    VARCHAR2(1),
    TRAVEL_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN TRAVELATTACHMENT.T_ATTACHMENT_NO_1 IS '첨부파일 코드';

COMMENT ON COLUMN TRAVELATTACHMENT.ORIGINAL_NAME_1 IS '첨부파일 이름';

COMMENT ON COLUMN TRAVELATTACHMENT.SAVED_NAME_1 IS '저장 이름';

COMMENT ON COLUMN TRAVELATTACHMENT.SAVE_PATH_1 IS '저장 경로';

COMMENT ON COLUMN TRAVELATTACHMENT.FILE_TYPE_1 IS '파일 타입';

COMMENT ON COLUMN TRAVELATTACHMENT.THUMBNAIL_PATH_1 IS '썸네일 경로';

COMMENT ON COLUMN TRAVELATTACHMENT.ATTACHMENT_STATUS_1 IS '판매상태 상태';

COMMENT ON COLUMN TRAVELATTACHMENT.TRAVEL_NO IS '투어상품번호';

COMMENT ON TABLE TRAVELATTACHMENT IS '상품등록첨부파일';

DROP INDEX 엔터티1_PK12;

CREATE UNIQUE INDEX 엔터티1_PK12 ON TRAVELATTACHMENT
( T_ATTACHMENT_NO_1 );

ALTER TABLE TRAVELATTACHMENT
DROP PRIMARY KEY;

ALTER TABLE TRAVELATTACHMENT
 ADD CONSTRAINT 엔터티1_PK12 PRIMARY KEY ( T_ATTACHMENT_NO_1 )
 USING INDEX 엔터티1_PK12;


DROP TABLE TRAVELREFUND;

CREATE TABLE TRAVELREFUND
(
    TRAVEL_RESERVATION_NO    VARCHAR2(100) NOT NULL,
    REFUND_REASON    VARCHAR2(4000),
    REFUND_PENALTY    NUMBER,
    REFUND_STATUS    VARCHAR2(10)
);

COMMENT ON COLUMN TRAVELREFUND.TRAVEL_RESERVATION_NO IS '투어예약번호';

COMMENT ON COLUMN TRAVELREFUND.REFUND_REASON IS '환불사유';

COMMENT ON COLUMN TRAVELREFUND.REFUND_PENALTY IS '위약금수수료';

COMMENT ON COLUMN TRAVELREFUND.REFUND_STATUS IS '환불상태';

COMMENT ON TABLE TRAVELREFUND IS '투어환불';

DROP INDEX 엔터티1_PK14;


ALTER TABLE TRAVELREFUND
DROP PRIMARY KEY;


DROP TABLE WARNING_HISTORY;

CREATE TABLE WARNING_HISTORY
(
    WARNING_NO    NUMBER NOT NULL,
    WARNING_DATE    DATE NOT NULL,
    WARNING_REASON    VARCHAR2(4000) NOT NULL,
    MEMBER_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN WARNING_HISTORY.WARNING_NO IS '경고이력번호';

COMMENT ON COLUMN WARNING_HISTORY.WARNING_DATE IS '경고일자';

COMMENT ON COLUMN WARNING_HISTORY.WARNING_REASON IS '경고사유';

COMMENT ON COLUMN WARNING_HISTORY.MEMBER_NO IS '경고대상가이드회원번호';

COMMENT ON TABLE WARNING_HISTORY IS '가이드경고이력';

DROP INDEX 엔터티1_PK4;

CREATE UNIQUE INDEX 엔터티1_PK4 ON WARNING_HISTORY
( WARNING_NO );

ALTER TABLE WARNING_HISTORY
DROP PRIMARY KEY;

ALTER TABLE WARNING_HISTORY
 ADD CONSTRAINT 엔터티1_PK4 PRIMARY KEY ( WARNING_NO )
 USING INDEX 엔터티1_PK4;


DROP TABLE WISHLIST;

CREATE TABLE WISHLIST
(
    MEMBER_NO    NUMBER NOT NULL,
    TRAVEL_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN WISHLIST.MEMBER_NO IS '회원번호';

COMMENT ON COLUMN WISHLIST.TRAVEL_NO IS '투어상품번호';

COMMENT ON TABLE WISHLIST IS '위시리스트';

DROP INDEX 엔터티2_PK;

CREATE UNIQUE INDEX 엔터티2_PK ON WISHLIST
( MEMBER_NO,TRAVEL_NO );

ALTER TABLE WISHLIST
DROP PRIMARY KEY;

ALTER TABLE WISHLIST
 ADD CONSTRAINT 엔터티2_PK PRIMARY KEY ( MEMBER_NO,TRAVEL_NO )
 USING INDEX 엔터티2_PK;


----------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------
--ALTER TABLE ASKBOARD ADD CHECK( ASKBOARD_CATEGORY IN ('COMPLAIN', 'ASK'));
--ALTER TABLE ASKBOARD ADD CHECK( ASKBOARD_STATUS IN ('ASK_ING', 'ANSWER_FINISH'));

--ALTER TABLE BOARD ADD CHECK( BOARD_CATEGORY IN ('TRAVEL_TIP', 'TRAVEL_CAUTION', 'TRAVEL_INFORMATION', 'NOTICE', 'FAQ'));

--ALTER TABLE BOARD_REVISE ADD CHECK( BOARD_CATEGORY IN ('TRAVEL_TIP', 'TRAVEL_CAUTION', 'TRAVEL_INFORMATION', 'NOTICE', 'FAQ'));
ALTER TABLE BOARD_REVISE ADD CHECK(  REVISE_CATEGORY IN ('TITLE', 'BODY'));

ALTER TABLE GUIDE_APPLICATION_HISTORY ADD CHECK( APPLICATION_STATUS IN ('FIRST_WAIT', 'FIRST_FINISH','SECOND_WAIT','SECOND_DONE','RETURN','REJECT'));

ALTER TABLE GUIDE_CALCULATE ADD CHECK(GUIDE_CALCULATE_STATUS IN ('1','2','3','4'));

ALTER TABLE GUIDE_RANK ADD CHECK(RANK_CODE IN ('1', '2','3'));

ALTER TABLE GUIDE_RANK_HISTORY ADD CHECK(RANK_CODE IN ('1', '2','3'));

ALTER TABLE MEMBER ADD CHECK(MEMBER_ROLE  IN('MEMBER','ADMIN','GUIDE'));
ALTER TABLE MEMBER ADD CHECK(GUIDE_RANK  IN('1','2','3','NULL'));
ALTER TABLE MEMBER MODIFY (MEMBER_ROLE DEFAULT 'MEMBER');
ALTER TABLE MEMBER MODIFY (MEMBER_ENROLLDATE DEFAULT SYSDATE);
ALTER TABLE MEMBER MODIFY (MEMBER_STATUS DEFAULT 'N');
ALTER TABLE MEMBER MODIFY (GUIDE_RANK DEFAULT NULL);
ALTER TABLE GUIDE_INFORMATION MODIFY (GUIDE_RANK DEFAULT '3');
ALTER TABLE GUIDE_INFORMATION MODIFY (GUIDE_APPROVE DEFAULT 'N');
ALTER TABLE GUIDE_INFORMATION MODIFY (GUIDE_STATUS DEFAULT 'N');
ALTER TABLE GUIDEATTACHMENT MODIFY (ATTACHMENT_STATUS_1 DEFAULT 'Y');


ALTER TABLE REVIEW ADD CHECK(REVIEW_GRADE IN ('1', '2','3','4','5'));
--ALTER TABLE TRAVEL ADD CHECK(TRAVEL_SELL_STATUS IN ('1', '2','3'));

ALTER TABLE TRAVELREFUND ADD CHECK(REFUND_STATUS IN ('REFUND_APPLY', 'REFUND_FINISH','REFUND_ING'));

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_MEMBER_NO"  MINVALUE 20 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_TRAVEL_RESERVATION_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_TRAVEL_RESERVATION_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 200 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_TRAVEL_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_TRAVEL_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 400 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_PAYMENT_HISTORY_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_PAYMENT_HISTORY_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 600 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_ASKBOARD_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_ASKBOARD_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 800 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_ASKBOARD_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_ASKBOARD_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_BOARD_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1200 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_WARNING_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_WARNING_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1400 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_PAYMENT_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_PAYMENT_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1600 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_APPLICATION_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_APPLICATION_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1800 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_TRAVEL_STATUS_HISTORY_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_TRAVEL_STATUS_HISTORY_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2000 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_CALCULATE_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_CALCULATE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2200 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_CALCULATE_NO;
CREATE SEQUENCE  "WEAREGO"."SEQ_CALCULATE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2200 CACHE 20 NOORDER  NOCYCLE ;


DROP SEQUENCE SEQ_R_ATTACHMENT_NO_1;
CREATE SEQUENCE  "WEAREGO"."SEQ_R_ATTACHMENT_NO_1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2800 CACHE 20 NOORDER  NOCYCLE ;

DROP SEQUENCE SEQ_T_ATTACHMENT_NO_1;
CREATE SEQUENCE  "WEAREGO"."SEQ_T_ATTACHMENT_NO_1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2400 CACHE 20 NOORDER  NOCYCLE ;


DROP SEQUENCE SEQ_G_ATTACHMENT_NO_1;
CREATE SEQUENCE  "WEAREGO"."SEQ_G_ATTACHMENT_NO_1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2600 CACHE 20 NOORDER  NOCYCLE ;


--회원정보 더미

INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '1', 'nk', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '냄켱'
   , 'skarod0401@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );

 INSERT
   INTO MEMBER
   (
     MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
   , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
   )
   VALUES
   (
     '2', 'guide', '$2a$10$F6V5KkfsFsJNSmspuIv76.oClnVEhSXXU01jmutY64ucSbwauNGQy', '가이드'
     , 'guide@gmail.com', '01012311231', 'N' ,'GUIDE', '21/02/19' , '3'
    );

INSERT 
 INTO MEMBER
( 
 MEMBER_NO, 
MEMBER_ID,
MEMBER_PWD, 
MEMBER_NICKNAME,
MEMBER_EMAIL,
MEMBER_PHONE,
MEMBER_STATUS,
MEMBER_ROLE,
MEMBER_ENROLLDATE,
GUIDE_RANK
)
VALUES
(
'3', 'admin', '$2a$10$5qF75CmRW5w2vv/UbRYdleOoeh/YBoBbLH4wxxL4F6VozK9ei1mNu',   '관리자',   'tnsfhr03@naver.com', '01082267150', 'N', 'ADMIN',   '21/02/21', NULL 
);

-- 가이드 정보 더미
 INSERT
   INTO GUIDE_INFORMATION
   (
     MEMBER_NO, GUIDE_NAME, GUIDE_EMAIL, GUIDE_BANK, GUIDE_ACCOUNT
   ,  GUIDE_INTRO, GUIDE_STATUS, GUIDE_RANK, GUIDE_WARNING_COUNT, GUIDE_APPROVE
   )
   VALUES
   (
     '2', '유재석', 'ujs@gmail.com', '국민은행', '590000-00-000000'
   ,  '관광 가이드 자신있씁니다!', 'Y', '3', '0', 'Y'  
   );


-- 가이드 등급별 수수료 
INSERT INTO GUIDE_RANK
(RANK_CODE, RANK_NAME, GUIDE_COMMISSION)
VALUES
(3, 'YELLOW', 0.2
);
INSERT INTO GUIDE_RANK
(RANK_CODE, RANK_NAME, GUIDE_COMMISSION)
VALUES
(2, 'ORANGE', 0.15
);
INSERT INTO GUIDE_RANK
(RANK_CODE, RANK_NAME, GUIDE_COMMISSION)
VALUES
(1, 'RED', 0.1
);
--회원 정보 등록


INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '4', 'jh', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '지훈'
   , 'jh@naver.com', '01012341231', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '5', 'mh', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '미화'
   , 'mh@naver.com', '01076543211', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '6', 'sr', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '승록'
   , 'sr@naver.com', '01056567676', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '7', 'th', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '태헌'
   , 'th@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '8', 'uj', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '유진'
   , 'uj@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '9', 'hjh', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '지훈'
   , 'hjh@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '10', 'ng', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '남규'
   , 'ng@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '11', 'ng', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '희상'
   , 'ng@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '12', 'mg', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '민기'
   , 'mg@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '13', 'wg', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '완규'
   , 'wg@naver.com', '01096817750', 'N', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '14', 'ms', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '민서'
   , 'ms@naver.com', '01096817750', 'Y', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '15', 'jhh', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '지환'
   , 'jhh@naver.com', '01096817750', 'Y', 'MEMBER', '21/02/18', NULL
   );
INSERT
  INTO MEMBER
  (
    MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE
  , MEMBER_STATUS, MEMBER_ROLE, MEMBER_ENROLLDATE, GUIDE_RANK
  )
  VALUES
  (
    '16', 'jh', '$2a$10$H8Z16HADHkPlyE/X5B8ZI.035UHTZ5f.6q85Y6REwcuoGdZtVUQrS', '진호'
   , 'jh@naver.com', '01096817750', 'Y', 'MEMBER', '21/02/18', NULL
   );

commit;